
#region Version

edition = "2021"
version = "Two"
required_version = "1.7.1"

#endregion Version

#region internal
emit_mode = "Files"
make_backup = false
force_explicit_abi = true
#endregion internal

#region output
color = "Auto"
unstable_features = false
disable_all_formatting = false
skip_children = false
show_parse_errors = true
error_on_line_overflow = false
error_on_unformatted = false
ignore = []
#endregion output

#region files
format_generated_files = true
merge_derives = true
#endregion files

#region width

# Used to set width to a specified percentage of `max_width`.
# ! Ignored if widths are explicitly set
use_small_heuristics = "Default"

max_width = 100

fn_call_width = 60
attr_fn_like_width = 70
struct_lit_width = 18
struct_variant_width = 35
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50
comment_width = 80
doc_comment_code_block_width = 100
short_array_element_width_threshold = 10
inline_attribute_width = 0
#endregion width

#region whitespace
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
indent_style = "Block"
space_before_colon = true
space_after_colon = true
spaces_around_ranges = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
#endregion whitespace

#region comments
wrap_comments = false
format_code_in_doc_comments = true
normalize_comments = false
normalize_doc_attributes = false
format_strings = false
#endregion comments

#region macros
format_macro_matchers = false
format_macro_bodies = true
skip_macro_invocations = []
#endregion macros

#region single line
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
#endregion single line

#region imports
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Preserve"
group_imports = "Preserve"
reorder_imports = true
reorder_modules = true
#endregion imports

#region alignment
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
force_multiline_blocks = false
fn_params_layout = "Tall"
#endregion alignment

#region braces
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
#endregion braces

#region trailing
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = false
#endregion trailing


use_try_shorthand = false
use_field_init_shorthand = false
condense_wildcard_suffixes = false
reorder_impl_items = false
type_punctuation_density = "Wide"
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = true
overflow_delimited_expr = false
hex_literal_case = "Preserve"
